# Generated by Django 4.2.16 on 2026-03-16 07:47

import apps.trainings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('compliance', 'Compliance'), ('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('hr', 'HR & Workplace'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', max_length=50)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_months', models.IntegerField(blank=True, help_text='Number of months before renewal is required', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=apps.trainings.models.certificate_upload_path)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='trainings.training')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['assigned', 'in_progress'])), fields=('training', 'employee'), name='unique_active_assignment'),
        ),
    ]
