# Generated by Django 4.2.16 on 2026-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('safety', 'Safety'), ('health', 'Health & Wellness'), ('fire_safety', 'Fire Safety'), ('hazmat', 'Hazardous Materials'), ('emergency', 'Emergency Preparedness'), ('electrical', 'Electrical Safety'), ('environmental', 'Environmental'), ('compliance', 'Compliance'), ('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('hr', 'HR & Workplace'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
